dist: trusty
sudo: false

branches:
  except:
    - gh-pages

language: node_js
node_js:
  - "8.9.4"

before_script:
  - npm install -g parcel

script: 
  - npm run production

deploy:
  skip_cleanup: true
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  on:
    branch: master
